# Generated by Django 2.0.2 on 2018-06-22 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivalArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '文章的栏目',
                'verbose_name_plural': '文章的栏目',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='文章编号')),
                ('edit_time', models.DateTimeField(verbose_name='修改时间')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('author', models.CharField(max_length=30, verbose_name='作者')),
                ('editor', models.CharField(max_length=30, verbose_name='编辑')),
                ('content', models.TextField(max_length=100000, verbose_name='内容')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
            },
        ),
        migrations.CreateModel(
            name='ArticlePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('all', '全部权限'), ('list', '可以查看'), ('create', '可以增加'), ('update', '可以修改'), ('destroy', '可以删除')], max_length=10, verbose_name='权限名称')),
            ],
            options={
                'verbose_name': '职务栏目权限',
                'verbose_name_plural': '用户职务-栏目权限表',
            },
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='栏目名称')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ArticleManagement.Column', verbose_name='上级栏目')),
            ],
            options={
                'verbose_name': '栏目',
                'verbose_name_plural': '栏目',
            },
        ),
        migrations.CreateModel(
            name='ArticleStat',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ArticleManagement.Article', verbose_name='文章')),
                ('stat', models.IntegerField(choices=[(0, '暂存'), (1, '发布')], default=1)),
            ],
            options={
                'verbose_name': '文章的状态',
                'verbose_name_plural': '文章的状态',
            },
        ),
        migrations.AddField(
            model_name='articlepermission',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleManagement.Column', verbose_name='栏目'),
        ),
        migrations.AddField(
            model_name='articlepermission',
            name='duty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='职务'),
        ),
        migrations.AddField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.User', verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='archivalarticles',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleManagement.Article', verbose_name='文章'),
        ),
        migrations.AddField(
            model_name='archivalarticles',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleManagement.Column', verbose_name='栏目'),
        ),
        migrations.AlterUniqueTogether(
            name='articlepermission',
            unique_together={('duty', 'column', 'permission')},
        ),
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('id', 'edit_time', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='archivalarticles',
            unique_together={('article', 'column')},
        ),
    ]
