# Generated by Django 2.0.2 on 2018-05-03 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
            ],
            options={
                'verbose_name': '教室/会议室',
                'verbose_name_plural': '教室/会议室',
            },
        ),
        migrations.CreateModel(
            name='RoomBorrowingApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(verbose_name='申请提交时间')),
                ('start_time', models.DateTimeField(verbose_name='申请开始时间')),
                ('end_time', models.DateTimeField(verbose_name='申请结束时间')),
                ('stat', models.CharField(max_length=30, verbose_name='申请状态')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ResourceBorrowingSystem.Room', verbose_name='申请教室')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserManagement.User', verbose_name='申请人')),
            ],
            options={
                'verbose_name': '教室/会议室借用申请',
                'verbose_name_plural': '教室/会议室借用申请',
            },
        ),
    ]
