# Generated by Django 2.0.7 on 2018-08-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceBorrowingSystem', '0002_auto_20180827_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryApplyReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=20, verbose_name='申请类型')),
            ],
            options={
                'verbose_name': '实验室申请理由',
                'verbose_name_plural': '实验室申请理由',
            },
        ),
        migrations.DeleteModel(
            name='ApplyReason',
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='name',
            field=models.CharField(max_length=20, verbose_name='实验室名称'),
        ),
    ]
