# Generated by Django 2.0.2 on 2018-09-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceBorrowingSystem', '0004_auto_20180829_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminuser',
            options={'verbose_name': '实验室管理员', 'verbose_name_plural': '实验室管理员'},
        ),
        migrations.AlterModelManagers(
            name='laboratoryborrowingapply',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='laboratoryborrowingapply',
            name='apply_id',
            field=models.CharField(max_length=25, verbose_name='申请编号'),
        ),
    ]
