# Generated by Django 2.0.2 on 2018-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceBorrowingSystem', '0005_auto_20180902_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratoryborrowingapply',
            name='stat',
            field=models.CharField(choices=[('已保存', '已保存'), ('已提交', '已提交'), ('审核中', '审核中'), ('排序中', '排序中'), ('申请通过', '申请通过'), ('申请不通过', '申请不通过')], max_length=30, verbose_name='申请状态'),
        ),
    ]
