# Generated by Django 2.0.2 on 2018-09-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResourceBorrowingSystem', '0006_auto_20180907_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratoryborrowingapply',
            name='registration_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='注册编号'),
        ),
    ]
