# Generated by Django 2.0.2 on 2018-04-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ArticleManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayColumn',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='序号')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArticleManagement.Column', verbose_name='栏目')),
            ],
            options={
                'verbose_name': '主页显示栏目',
                'verbose_name_plural': '主页显示栏目',
            },
        ),
        migrations.CreateModel(
            name='NavbarObject',
            fields=[
                ('serial_number', models.FloatField(primary_key=True, serialize=False, verbose_name='序号')),
                ('name', models.CharField(max_length=25, verbose_name='名称')),
                ('herf', models.CharField(max_length=100, verbose_name='相对路径')),
            ],
            options={
                'verbose_name': '导航栏内容',
                'verbose_name_plural': '导航栏内容',
            },
        ),
    ]
