# Generated by Django 2.0.2 on 2018-05-20 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='部门')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Department', verbose_name='上级部门')),
            ],
            options={
                'verbose_name': '部门',
                'verbose_name_plural': '部门列表',
            },
        ),
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='职务名称')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Department', verbose_name='部门')),
            ],
            options={
                'verbose_name': '职务',
                'verbose_name_plural': '职务列表',
            },
        ),
        migrations.CreateModel(
            name='Duty_Permition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(verbose_name='权限等级')),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Duty', verbose_name='职务')),
            ],
            options={
                'verbose_name': '职务权限',
                'verbose_name_plural': '职务权限对应表',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='专业')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
            },
        ),
        migrations.CreateModel(
            name='Permition',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='权限名称')),
                ('superior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Permition', verbose_name='上级权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限列表',
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Student_Class',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='班级')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
            },
        ),
        migrations.CreateModel(
            name='Student_Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='年级')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '年级',
                'verbose_name_plural': '年级',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='学工号')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('pwd', models.CharField(max_length=25, verbose_name='密码')),
                ('stat', models.CharField(blank=True, max_length=20, null=True, verbose_name='用户状态')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户列表',
            },
        ),
        migrations.CreateModel(
            name='User_Duty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Duty', verbose_name='职务')),
            ],
            options={
                'verbose_name': '用户职务',
                'verbose_name_plural': '用户职务对应表',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserManagement.User', verbose_name='学生用户')),
                ('birthday', models.DateField(verbose_name='出生日期')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='UserManagement.User', verbose_name='教师用户')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
            },
        ),
        migrations.AddField(
            model_name='user_duty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.User', verbose_name='用户'),
        ),
        migrations.AddField(
            model_name='student_class',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='UserManagement.Student_Grade', verbose_name='年级'),
        ),
        migrations.AddField(
            model_name='duty_permition',
            name='permition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Permition', verbose_name='权限'),
        ),
        migrations.AlterUniqueTogether(
            name='user_duty',
            unique_together={('user', 'duty')},
        ),
        migrations.AlterUniqueTogether(
            name='student_grade',
            unique_together={('name', 'major')},
        ),
        migrations.AddField(
            model_name='student_class',
            name='headmaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='headmaster_teacher', to='UserManagement.Teacher', verbose_name='班导师'),
        ),
        migrations.AddField(
            model_name='student_class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='instructor_teacher', to='UserManagement.Teacher', verbose_name='辅导员'),
        ),
        migrations.AddField(
            model_name='student',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='UserManagement.Teacher', verbose_name='导师'),
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='UserManagement.Student_Class', verbose_name='班级'),
        ),
        migrations.AlterUniqueTogether(
            name='duty_permition',
            unique_together={('permition', 'duty')},
        ),
        migrations.AlterUniqueTogether(
            name='duty',
            unique_together={('name', 'department')},
        ),
    ]
