# Generated by Django 2.0.2 on 2018-04-22 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=5)),
                ('pwd', models.CharField(max_length=25)),
            ],
        ),
    ]
