# Generated by Django 2.0.2 on 2018-09-01 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='user',
            name='qq',
            field=models.CharField(max_length=20, null=True, verbose_name='QQ'),
        ),
    ]
